In [2]:
import pandas as pd

In [36]:
departamentos = pd.read_csv(r"C:\Users\SAMSUNG\Desktop\Projeto LACEDA\dados\departamentos.csv")
filiais = pd.read_csv(r"C:\Users\SAMSUNG\Desktop\Projeto LACEDA\dados\filiais.csv")
funcionarios = pd.read_csv(r"C:\Users\SAMSUNG\Desktop\Projeto LACEDA\dados\funcionarios.csv")

In [37]:
funcionarios.duplicated().sum()

np.int64(0)

In [38]:
funcionarios["data_admissao"] = funcionarios["data_admissao"].str.replace("/","-")

In [41]:
funcionarios["data_admissao"] = pd.to_datetime(
    funcionarios["data_admissao"],
    format="mixed",
)

In [49]:
funcionarios["data_promocao"] = funcionarios["data_promocao"].str.replace("/","-")

funcionarios["data_promocao"] = pd.to_datetime(
    funcionarios["data_promocao"],
    format="mixed",
)

In [43]:
funcionarios_filtrados = funcionarios[
    (funcionarios["genero"] != "Feminino") &
    (funcionarios["genero"] != "Masculino") &
    (funcionarios["genero"] != "Não-binário")
]
funcionarios_filtrados

Empty DataFrame
Columns: [id_colaborador, nome, genero, nivel, data_admissao, data_promocao, salario_base, percentual_bonus, id_departamento, id_filial, id_reporta_a, processos_actifs, horas_extras_mes, score_satisfacao, home_office, status_atual]
Index: []

In [44]:
funcionarios["genero"] = funcionarios["genero"].replace("Fem","Feminino")

In [68]:
funcionarios["status_atual"].unique()

<StringArray>
['Ativo', 'Desligado']
Length: 2, dtype: str

In [54]:
funcionarios["data_promocao"].dropna()

8     2023-12-29
11    2025-11-07
13    2023-07-07
14    2022-10-04
28    2022-07-15
         ...
634   2025-06-11
636   2026-04-15
637   2025-03-15
638   2022-12-04
647   2017-03-04
Name: data_promocao, Length: 216, dtype: datetime64[us]

In [72]:
funcionarios["salario_base"] = funcionarios["salario_base"].str.replace(
    r"^R\$\s*",
    "",
    regex=True
)
funcionarios

,id_colaborador,nome,genero,nivel,data_admissao,data_promocao,salario_base,percentual_bonus,id_departamento,id_filial,id_reporta_a,processos_actifs,horas_extras_mes,score_satisfacao,home_office,status_atual
0,1,Isabela Carvalho 1,Não-binário,Júnior,2024-07-09,NaT,"3834,82",0,10,1,501.0,14,8,NaN,False,Ativo
1,2,Samuel Teixeira 2,Não-binário,Pleno,2022-05-09,NaT,"7267,8",15,10,2,300.0,16,8,4.9,True,Desligado
2,3,Diego Santos 3,Masculino,Júnior,2025-01-02,NaT,"4771,24",1,10,1,501.0,29,11,4.7,True,Ativo
3,4,Carla Oliveira 4,Não-binário,Pleno,2020-04-03,NaT,"7819,21",14,30,2,300.0,32,13,3.5,False,Desligado
4,5,Carla Oliveira 5,Não-binário,Júnior,2025-09-15,NaT,"4452,47",5,20,3,300.0,46,42,2.2,False,Desligado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
645,646,Bruno Souza 646,Masculino,Júnior,2024-08-05,NaT,"3519,69",9,10,1,300.0,28,18,4.7,True,Ativo
646,647,Diego Santos 647,Não-binário,Pleno,2020-09-23,NaT,"6590,93",16,40,2,502.0,14,10,NaN,True,Desligado
647,648,Olivia Barbosa 648,Feminino,Sócio,2013-03-14,2017-03-04,"18228,69",51,30,1,NaN,15,19,3.4,True,Ativo
648,649,Mariana Rocha 649,Feminino,Pleno,2022-10-25,NaT,"6501,22",16,40,2,501.0,21,8,3.9,True,Desligado
649,650,Natan Alves 650,Não-binário,Júnior,2024-04-21,NaT,"4521,74",4,30,4,300.0,19,4,4.2,True,Ativo

In [73]:
funcionarios["salario_base"] = funcionarios["salario_base"].str.replace(".",",")
funcionarios

,id_colaborador,nome,genero,nivel,data_admissao,data_promocao,salario_base,percentual_bonus,id_departamento,id_filial,id_reporta_a,processos_actifs,horas_extras_mes,score_satisfacao,home_office,status_atual
0,1,Isabela Carvalho 1,Não-binário,Júnior,2024-07-09,NaT,"3834,82",0,10,1,501.0,14,8,NaN,False,Ativo
1,2,Samuel Teixeira 2,Não-binário,Pleno,2022-05-09,NaT,"7267,8",15,10,2,300.0,16,8,4.9,True,Desligado
2,3,Diego Santos 3,Masculino,Júnior,2025-01-02,NaT,"4771,24",1,10,1,501.0,29,11,4.7,True,Ativo
3,4,Carla Oliveira 4,Não-binário,Pleno,2020-04-03,NaT,"7819,21",14,30,2,300.0,32,13,3.5,False,Desligado
4,5,Carla Oliveira 5,Não-binário,Júnior,2025-09-15,NaT,"4452,47",5,20,3,300.0,46,42,2.2,False,Desligado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
645,646,Bruno Souza 646,Masculino,Júnior,2024-08-05,NaT,"3519,69",9,10,1,300.0,28,18,4.7,True,Ativo
646,647,Diego Santos 647,Não-binário,Pleno,2020-09-23,NaT,"6590,93",16,40,2,502.0,14,10,NaN,True,Desligado
647,648,Olivia Barbosa 648,Feminino,Sócio,2013-03-14,2017-03-04,"18228,69",51,30,1,NaN,15,19,3.4,True,Ativo
648,649,Mariana Rocha 649,Feminino,Pleno,2022-10-25,NaT,"6501,22",16,40,2,501.0,21,8,3.9,True,Desligado
649,650,Natan Alves 650,Não-binário,Júnior,2024-04-21,NaT,"4521,74",4,30,4,300.0,19,4,4.2,True,Ativo

In [75]:
funcionarios.to_csv("funcionarios_tratado.csv", index=False)